services:
  apache-kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://apache-kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@apache-kafka:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    networks:
      - social

  metric:
    image: analysis-metric:latest
    ports:
      - "9300:9300"
    depends_on:
      - apache-kafka
    volumes:
      - ./data/analysis-metric/metric:/app/metric
      - ./data/analysis-metric/logs:/app/logs
    networks:
      - social

  netflix-discovery:
    image: netflix-discovery:latest
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - social

  gateway:
    image: gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - netflix-discovery
    volumes:
      - ./data/gateway/logs:/app/logs
    networks:
      - social

  user-manager:
    image: user-manager:latest
    ports:
      - "9001:9001"
    depends_on:
      - netflix-discovery
      - apache-kafka
    volumes:
      - ./data/user-manager/logs:/app/logs
    networks:
      - social

  file-service:
    image: file-service:latest
    ports:
      - "9200:9200"
    depends_on:
      - netflix-discovery
    volumes:
      - ./data/file-service/logs:/app/logs
    networks:
      - social

  social-service:
    image: social-service:latest
    ports:
      - "9003:9003"
    depends_on:
      - netflix-discovery
      - apache-kafka
    volumes:
      - ./data/social-service/logs:/app/logs
    networks:
      - social

  messenger:
    image: messenger:latest
    ports:
      - "9002:9002"
    depends_on:
      - netflix-discovery
      - apache-kafka
    volumes:
      - ./data/messenger/logs:/app/logs
    networks:
      - social

networks:
  social:
    external: true