server:
  port: 8080

spring:
  application:
    name: gateway

  # Route configuration
  cloud:
    gateway:
      routes:
        - id: block-access-inner
          uri: no://op  # Deny all traffic
          predicates:
            - Path=/*/inner/**  # Block any path that contains /{service}/inner/...
          filters:
            - SetStatus=403

        - id: user-manager
          uri: http://localhost:9001
          predicates:
            - Path=/user-manager/**
          filters:
            - StripPrefix=1

        - id: messenger
          uri: http://localhost:9002
          predicates:
            - Path=/messenger/**

        - id: social-service
          uri: http://localhost:9003
          predicates:
            - Path=/social-service/**

      discovery:
        locator:
          enabled: false               # enable {true} when use eureka netflix
          lowerCaseServiceId: true

      httpclient:
        connect-timeout: 3000
        response-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 0
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: true